#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
  path: /logout
  controller: App\Controller\HomeController::index

/:
    path: /{_locale}/
    controller: App\Controller\HomeController::index
    requirements:
        _locale: en|fr